### ISSUE TITLE
how to run DeMixT

### ISSUE THREAD

**Issue by sunnyyakima** [wwylab/DeMixT#11]
Hi,
Happy new year!
I am new to deconvolution of tumor cell. I have TPM results from two RNAseq samples. How can I do the deconvolution using DeMixT? for the function: what are data.Y and data.comp1 in my case?
DeMixT(data.Y = ??, data.comp1 = ??, if.filter = FALSE) 

Thanks

**Comment by pengyang0411** [comment]
Hi,

Thanks for interesting in our work. For your case, data.Y is the mixed tumor matrix, with each row and column corresponds gene and mixed tumor sample, respectively; data.comp1 is the normal reference matrix, with each row and column corresponds gene and pure normal sample; if.filter = TRUE, a subset of genes will be selected to estimate tumor proportion of each sample based on genes' differential expressions and we recommend to set if.filter = TRUE, which will reduce the noise introduced by genes while doing deconvolution. The DeMixT function will return a list contains pi (estimated tumor proportions) and deconvoluted tumor and normal expression profile. Please use commend ?DeMixT in R for more specific details. 

Besides, we are going to release a new version, which implement a new gene selection method and is much improved in user friendliness. 

If you have more question, please don't hesitate to ask me.

Happy new year,
Peng

**Comment by sunnyyakima** [comment]
Thanks for your reply!
where can I get "the normal reference matrix"?

**Comment by ShaolongCao** [comment]
Hi Sunnyyakima,

The "normal reference matrix" means expression profile from normal tissue which depends on which cancer type your data come from. For example, if your tumor RNAseq data come from prostate cancer, the normal reference should be RNAseq data from normal prostate tissue or tumor adjacent normal prostate tissue. 
Another problem is that you only have two RNAseq samples from tumor. It is different to achieve reliable results of DeMixT with such small amount of sample size. If you can provide more detailed information, we may help you figure out a solution.

Best,
Shaolong
