### ISSUE TITLE
Missing function in preproccesing

### ISSUE THREAD

**Issue by AdamLaang** [wwylab/DeMixT#21]
Hi! 

I'm following the [tutorial](https://wwylab.github.io/DeMixT/tutorial.html) and noticed that a function is not included.
newSeqCountSet (line 139) in the source of DeMixT_preprocessing.R is nowhere to be found and therefore causing the error: 

 Error in newSeqCountSet(as.matrix(newt), designs) : 
  could not find function "newSeqCountSet"

Best regards,
Adam

**Comment by jiyunmaths** [comment]
@AdamLaang Thanks for your question. The function "newSeqCountSet" is from the library "DSS". As mentioned in the tutorial, please load the following libraries as the first step of running DeMixT:

```
library(DeMixT)
library(dplyr)
library(dendextend)
library(psych)
library(DSS)
library(ClassDiscovery)
```
Please let me know if you have any questions.

**Comment by jiyunmaths** [comment]
This issue was addressed.
