### ISSUE TITLE
nthread was not taken

### ISSUE THREAD

**Issue by arraytools** [wwylab/DeMixT#23]
Hello,

It seems the 'nthread' parameter was not taken when the "GS" (default) method was used in DeMixT(). When I checked the source code, https://github.com/wwylab/DeMixT/blob/master/R/DeMixT.R#L180
the nthread parameter was not passed to the DeMixT_GS() function and (parallel::detectCores() - 1 ) was used instead.

-Ming

**Comment by jiyunmaths** [comment]
@arraytools Thanks for your question. Can I ask if you are using a MacOS machine to run DeMixT? As we state in the ReadMe file, DeMixT relies on OpenMP for parallel computing. Starting from R 4.00, R no longer supports OpenMP on MacOS, meaning the user can only run DeMixT with one core on MacOS. For this scenario,  DeMixT() ignores the nthread you specify and only uses one core. We recommend you to run DeMixT using a Linux or Windows machine. Thanks.

**Comment by arraytools** [comment]
thank you for the reply. I run DeMixT on a linux cluster. I specify nthread=64 in DeMixT() with "GS" method and the code still uses 127 cpus which is obvious over the limit of the specification of the job. As I point out the source code, the call to DeMixT_GS() does not honor the nthread parameter from DeMixT() function.

**Comment by jiyunmaths** [comment]
@arraytools I am sorry for the problem. I fixed it. The GitHub was updated. Please install DeMixT again using devtools::install_github("wwylab/DeMixT"). Thanks!

**Comment by arraytools** [comment]
This works. Thanks!

**Comment by jiyunmaths** [comment]
The issues was addressed.
