### ISSUE TITLE
data standardization

### ISSUE THREAD

**Issue by xuxingyubio** [wwylab/DeMixT#27]
Dear DeMixT community and developers,

This is a very important piece of software. Now I'm having some problems.

I have obtained an expression matrix through the deconvolution process, which seems to be a raw expression matrix containing partial genes. How can I normalize it so that the samples can be compared?

**Comment by jiyunmaths** [comment]
@xuxingyubio Thanks for using DeMixT. The input to DeMixT is a raw expression matrix, including data from the mixed tumor to be deconvoluted and the normal as a reference. So you do not need to normalize the data. Typically, the number of input genes is ~9000, from which DeMixT identifies a subset (e.g., 1500-2500 genes) that are used for parameter estimation. Can I ask how many genes do you have at the beginning? How many of them are remaining after the preprocessing step (`DeMixT_preprocess`)?

**Comment by xuxingyubio** [comment]
After the preprocessing step, there is 9021 genes. I finally obtained a reverse rolling matrix containing 8946 genes, but this matrix is supposed to be an original matrix that does not contain all genes. How should I normalize this matrix so that the samples can be compared?

**Comment by jiyunmaths** [comment]
@xuxingyubio The number of genes seems to be enough. In the preprocess step, DeMixT already applies a scale normalization to balance the expression levels across samples. So you do not need to do further normalization. You can now run the deconvolution step (step4 in the tutorial https://wwylab.github.io/DeMixT/tutorial.html).

**Comment by xuxingyubio** [comment]
I have finished running this process. It seems that the output res$ExprT is a raw expression matrix containing 8946 genes, and res$ExprT only contains some of the genes. How can I normalize res$ExprT so that the samples can be compared?

**Comment by wwylab** [comment]
No normalization should be done on the output data.

**Comment by wwylab** [comment]
This issue is closed.
